# Generated by Django 2.1.3 on 2018-11-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_keeping', '0002_auto_20181116_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Bank name'),
        ),
    ]
