# Generated by Django 2.1.3 on 2018-11-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_keeping', '0003_auto_20181121_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=128, null=True, verbose_name='Slug'),
        ),
    ]
