# Generated by Django 2.1.3 on 2018-11-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_keeping', '0004_auto_20181121_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(max_length=5, verbose_name='Currency'),
        ),
    ]
