# Generated by Django 2.1.3 on 2019-01-22 05:57

import account_keeping.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=25)),
                ('routing_number', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=128, verbose_name='Slug')),
                ('initial_amount', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Initial amount')),
                ('total_amount', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Total amount')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('invoice_date', models.DateField(verbose_name='Invoice date')),
                ('invoice_type', models.CharField(choices=[('w', 'withdrawal'), ('d', 'deposit'), ('m', 'monthly'), ('eo', 'extra-ordinary')], max_length=2, verbose_name='Invoice type')),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Active'), ('c', 'Canceled'), ('i', 'Invoiced')], default='a', max_length=10)),
                ('order_type', models.CharField(choices=[('w', 'withdrawal'), ('d', 'deposit'), ('m', 'monthly'), ('eo', 'extra-ordinary')], max_length=1, verbose_name='Order type')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Order date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount_net', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=18, verbose_name='Amount net')),
                ('vat', models.DecimalField(decimal_places=10, default=0, help_text='sales tax', max_digits=14, verbose_name='Sales tax')),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=18, verbose_name='Amount gross')),
                ('value_net', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Value net')),
                ('value_gross', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Value gross')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment date')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='order_files', verbose_name='PDF')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date', '-pk'],
            },
            bases=(models.Model, account_keeping.models.AmountMixin),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_date', models.DateField(verbose_name='Item date')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount_gross', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Amount gross')),
            ],
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Payee')),
            ],
            options={
                'verbose_name': 'Payee',
                'verbose_name_plural': 'Payees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('w', 'withdrawal'), ('d', 'deposit'), ('p', 'pending')], max_length=1, verbose_name='Transaction type')),
                ('transaction_date', models.DateField(verbose_name='Transaction date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('invoice_number', models.CharField(blank=True, max_length=256, verbose_name='Invoice No.')),
                ('amount_net', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=18, verbose_name='Amount net')),
                ('vat', models.DecimalField(decimal_places=10, default=0, max_digits=14, verbose_name='VAT')),
                ('amount_gross', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=18, verbose_name='Amount gross')),
                ('value_net', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Value net')),
                ('value_gross', models.DecimalField(decimal_places=10, default=0, max_digits=18, verbose_name='Value gross')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account_keeping.Account', verbose_name='Account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='account_keeping.Category', verbose_name='Category')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='account_keeping.Invoice', verbose_name='Invoice')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account_keeping.Transaction', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date', '-pk'],
            },
            bases=(account_keeping.models.AmountMixin, models.Model),
        ),
    ]
