# Generated by Django 2.1.3 on 2018-12-15 18:11

import os

from django.db import connection, migrations

def load_data_from_sql(apps, schema_editor):
	from django.conf import settings
	BASE_DIR= settings.BASE_DIR
	file_path = os.path.join(BASE_DIR, 'account_keeping', 'custom_sql')
	file_path = os.path.join(os.path.dirname(__file__), '../custom_sql/', 'postgresql.sql')
	sql_statement = open(file_path).read()
	with connection.cursor() as c:
		c.execute(sql_statement)

#migrate_data =  load_data_from_sql('postgresql.sql')



class Migration(migrations.Migration):

    dependencies = [
        ('account_keeping', '0001_initial'),
    ]

    operations = [
    migrations.RunPython(load_data_from_sql)
    # 	migrations.RunSQL(
    # 		[
    # 			'''
				# CREATE OR REPLACE FUNCTION dateYear(invoice_date date)
				# RETURNS integer AS $$
				# BEGIN
				# 	RETURN YEAR(invoice_date);
				# END;
				# $$ LANGUAGE plpgsql
				# IMMUTABLE;
				# CREATE OR REPLACE FUNCTION dateMonth(invoice_date date)
				# RETURNS integer AS $$
				# BEGIN
				# 	RETURN MONTH(invoice_date);
				# END;
				# $$ LANGUAGE plpgsql
				# IMMUTABLE;
				# CREATE UNIQUE INDEX IF NOT EXISTS uniqueMonthlyInvoicePerMonth
				# ON account_keeping_invoice (condo_id, dateYear(account_keeping_invoice.invoice_date), dateMonth(account_keeping_invoice.invoice_date))
				# WHERE invoice_type = 'm';
    # 			'''
    # 		]
    # 	)
    ]
