# Generated by Django 2.1.3 on 2018-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_keeping', '0003_postgresql_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=256, verbose_name='Invoice No.'),
        ),
    ]
