# Generated by Django 2.1.3 on 2018-12-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_keeping', '0005_auto_20181220_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('w', 'withdrawal'), ('d', 'deposit'), ('m', 'monthly'), ('eo', 'extra-ordinary')], max_length=2, verbose_name='Invoice type'),
        ),
    ]
