# Generated by Django 2.1.3 on 2018-12-22 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_keeping', '0007_auto_20181221_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='account_keeping.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('c', 'Canceled'), ('i', 'Invoiced')], default='a', max_length=10),
        ),
    ]
