# Generated by Django 2.1.3 on 2018-12-22 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_keeping', '0009_auto_20181222_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='account_keeping.Order'),
        ),
    ]
