# Generated by Django 2.1.3 on 2018-11-28 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_keeping', '0004_auto_20181127_0841'),
        ('condo_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account_keeping.Account')),
                ('condo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='condo_manager.Condo')),
            ],
            bases=('account_keeping.account',),
        ),
    ]
