# Generated by Django 2.1.3 on 2018-11-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0002_auto_20181117_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='condo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='condo_manager.Condo', verbose_name='Condominium'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='initial_balance',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=50, verbose_name='initial balance'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='name',
            field=models.CharField(help_text='House number or name; apartment number, etc', max_length=20, verbose_name='Property name'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='condo_manager.Resident'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='percentage representation'),
        ),
    ]
