# Generated by Django 2.1.3 on 2018-11-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0002_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
