# Generated by Django 2.1.3 on 2018-11-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0002_auto_20181129_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='condo',
            name='razon_social',
            field=models.CharField(default='residencias kiara', max_length=25, verbose_name='Condo name'),
            preserve_default=False,
        ),
    ]
