# Generated by Django 2.1.3 on 2018-11-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0003_condo_razon_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Fiscal Number'),
        ),
    ]
