# Generated by Django 2.1.3 on 2018-11-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0003_auto_20181129_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
