# Generated by Django 2.1.3 on 2018-12-02 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0005_auto_20181202_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='rentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condo_manager.Rentee', verbose_name='Rentee'),
        ),
    ]
