# Generated by Django 2.1.3 on 2018-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0005_auto_20181120_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='balance',
            field=models.DecimalField(decimal_places=4, max_digits=25, verbose_name='current debt'),
        ),
    ]
