# Generated by Django 2.1.3 on 2018-11-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0006_auto_20181120_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='active',
            field=models.BooleanField(default=True, help_text='Condominiums will be deactivated when percentage falls below 99.75'),
        ),
        migrations.AlterField(
            model_name='condo',
            name='terms_accepted',
            field=models.BooleanField(default=False, null=True, verbose_name='Terms'),
        ),
    ]
