# Generated by Django 2.1.3 on 2018-11-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0007_auto_20181121_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condo',
            name='approved',
            field=models.NullBooleanField(choices=[(None, 'Not evaluated'), (True, 'Approved'), (False, 'Rejected')], default=None, verbose_name='Approved'),
        ),
    ]
