# Generated by Django 2.1.3 on 2018-12-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0007_auto_20181203_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='rented',
        ),
    ]
