# Generated by Django 2.1.3 on 2018-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0008_auto_20181121_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='percentage representation'),
        ),
    ]
