# Generated by Django 2.1.3 on 2018-12-04 06:52

import condo_manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0010_remove_inmueble_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condo',
            old_name='razon_social',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='share',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[condo_manager.validators.validate_postitive], verbose_name='percentage representation'),
        ),
    ]
