# Generated by Django 2.1.3 on 2018-12-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condo_manager', '0011_auto_20181204_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentee',
            name='terms_accepted',
            field=models.BooleanField(default=False, null=True, verbose_name='Terms'),
        ),
        migrations.AddField(
            model_name='resident',
            name='terms_accepted',
            field=models.BooleanField(default=False, null=True, verbose_name='Terms'),
        ),
    ]
